project:
  type: website
  output-dir: docs
website:
  title: "Jake Beardsley Website"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jrbeardsley/
format:
  html:
    theme: cosmo
    css: styles.css



